### ISSUE TITLE
It is not possible to select a script language in rest.document/update-with-script

### ISSUE THREAD

**Issue by puszczyk** [clojurewerkz/elastisch#122]
Hi,

In `clojurewerkz.elastisch.rest.document/update-with-script` the request body is generated like this:
```clojure
(defn update-with-script
  "Updates a document using a script"
  ([^Connection conn index mapping-type id script]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id)
                {:body {:script script}}))
  ([^Connection conn index mapping-type id script params]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id)
                {:body {:script script :params params}})))
```

But if we look at the [update api](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-update.html) it should also accept a script language as an optional parameter (grated that this is not well documented in ES); so it should be something like 

```clojure
([^Connection conn index mapping-type id script lang params]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id)
                {:body {:script script :lang lang :params params}})))
```

This is even more important as ES plans to move from `mvel` to `groovy` as a default scripting language ([src](http://www.elasticsearch.org/blog/scripting/)). I'd be even better to add a varargs support like in e.g. [`update-with-partial-doc`](https://github.com/clojurewerkz/elastisch/blob/master/src/clojurewerkz/elastisch/rest/document.clj#L68)

```clojure
(defn update-with-partial-doc
  "Updates an existing document in the search index with given partial document"
  ([^Connection conn index mapping-type id partial-doc]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id) {:body partial-doc}))
  ([^Connection conn index mapping-type id partial-doc & args]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id)
                {:body partial-doc :query-params (ar/->opts args)})))
```

Please also notice the discrepancy between the two implementations. In `update-with-script` you provide the script body itself, but in `update-with-partial-doc` you need to provide the `:doc` param manually - [example taken from the tests](https://github.com/clojurewerkz/elastisch/blob/master/test/clojurewerkz/elastisch/rest_api/update_test.clj#L75)

```clojure
(doc/update-with-partial-doc conn index-name index-type id {:doc { :country "India" }})
```

I didn't found any tests for `update-with-script`. In my use case all the scripts are groovy, so I ended up with a function which is more or less a copy-paste of yours, but additionally appends this `:lang "groovy"` to the body.

I'd be happy to fix the *clojurewerkz/elastisch* implementation plus add a test case for udpate with script, but pls let me know what is the preferred way? Maybe add optional args (`& args`) to the second version and append them to the body with `(ar/->opts args)`

```clojure
(defn update-with-script
  "Updates a document using a script"
  ([^Connection conn index mapping-type id script]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id)
                {:body {:script script}}))
  ([^Connection conn index mapping-type id script params & args]
     (rest/post conn (rest/record-update-url conn
                                             index mapping-type id)
                {:body {:script script :params params (ar/->opts args)}})))
```

What do you think?

**Comment by michaelklishin** [comment]
I believe this was fixed by #123.
