### ISSUE TITLE
build-local-node only supports client mode due to hardcoding

### ISSUE THREAD

**Issue by wesleyhall** [clojurewerkz/elastisch#133]
Hey folks, 

The build-local-node function in clojurewerkz.elastisch.native has a hardcoded line that sets the client mode of the built node to true meaning that this function cannot be used to start an independent and functional elasticsearch node. This is a bit of a shame because something like this is quite useful for testing and development. Is there any reason why the current code fixes this value to client = true with no option to override? 

I have a fork which changes this function thusly...

    (defn ^Node build-local-node
      [settings & {:keys [client] :or {client true}}]
        (let [is (cnv/->settings settings)
               nb (.. NodeBuilder nodeBuilder
                      (settings is)
                      (client client))]
        (.build ^NodeBuilder nb)))

...but i'm not sure if this is ideal. Perhaps an overloaded function instead? 

I think it would be quite nice to have this feature.

**Comment by michaelklishin** [comment]
@wesleyhall this looks OK to me. The point of `build-local-node` is to be used in development and testing. Please submit a PR.

**Comment by wesleyhall** [comment]
Great, all yours :)

**Comment by michaelklishin** [comment]
Fixed by #134, thank you!
