### ISSUE TITLE
unregister-query response format is different between REST and native clients

### ISSUE THREAD

**Issue by parkjaehyuck** [clojurewerkz/elastisch#142]
sorry I can't write English. native api used. not REST Api.

watch below source code.

request to server unregister percolator.. 

request query :

``` clojure
(pcl/unregister-query native-conn "my_index" "aa::8f0fdfc9-8a13-40ea-83bb-e8750668bdd7")
```

response 
``` clojure
{:ok false, :found false, :found? false, :_index ".percolator", :_type "my_index", :_version 1, :_id "aa::8f0fdfc9-8a13-40ea-83bb-e8750668bdd7"}
```

`_index : .percolator` <-- I think this is wrong. 

I think this is correct:
``` clojure
{ :_index "my_index", :_type ".percolator", :_version 1, :_id "aa::8f0fdfc9-8a13-40ea-83bb-e8750668bdd7"}
```

REST api work well.
Native api not work..

thank.

**Comment by michaelklishin** [comment]
Thank you, I agree, this looks like an issue in the native client.
