### ISSUE TITLE
scroll-id larger than 4k

### ISSUE THREAD

**Issue by nikopol** [clojurewerkz/elastisch#150]
Hello,
With Elasticsearch 1.4, making a scroll search on multiple indexes can generate a scroll-id larger than 4k. Such scroll-id cannot be used in HTTP/GET method : that's generated this exception on Elasticsearch side :

org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: An HTTP line is larger than 4096 bytes.

and of course this exception on the elastisch side : 

org.apache.http.NoHttpResponseException: my.host:9200 failed to respond

The rest scroll method should use a post method with the scroll_id in the body.

**Comment by michaelklishin** [comment]
Fixed by #152. I'll cut a `2.1.x` release in the upcoming days.
