### ISSUE TITLE
Is native local node supposed to be used in production?

### ISSUE THREAD

**Issue by martinhynar** [clojurewerkz/elastisch#153]
Hi,

I need to sort things (at least for myself) on using various native client options. According to ES documentation, there are 2 possibilities - TransportClient and NodeClient. The transport client option is  clear to me and its configuration using elastisch is straightforward. In my application, I want to go the node client path to connect to cluster, with disabled autodiscovery and given node seed list. So, to get the connection to ES, I do

```
(let [node (esn/build-local-node{"cluster.name"                        "elasticsearch"
                                 "discovery.zen.ping.multicast.enabled" false
                                 "discovery.zen.ping.unicast.hosts"     cluster-nodes })]
     (esn/start-local-node node)
     (esn/connect-to-local-node node)
)
```

This shall give me client connection to ES cluster. But I am not sure if I shall do this. The docstring on `connect-to-local-node` claims it is supposed to be for automated testing. Is my setup correct?

**Comment by michaelklishin** [comment]
It was added for automated testing. It makes little sense to run a local node in production. You should be able to specify options such as `discovery.*` for a transport client as well.

**Comment by martinhynar** [comment]
OK, now I understand meaning of 'local' in this context. Because I was thinking about that as 'local to application' and not that everything runs on localhost. Thanks!
