### ISSUE TITLE
Keyword keys don't work in index settings

### ISSUE THREAD

**Issue by mnylen** [clojurewerkz/elastisch#158]
Calling `(esi/create conn name :mappings mappings :settings settings)` allows keywordized keys for `mappings` map, but not for `settings`

Using keywordized keys in `settings` map causes this exception to be thrown:

    ClassCastException java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.String

**Comment by michaelklishin** [comment]
@mnylen this is an overlook, there is no big idea behind the difference. Feel free to take a look into this. Note that we have our own keywordisation function, which is a lot more efficient than `clojure.walk/keywordize-keys`.

**Comment by mnylen** [comment]
I'll add ChangeLog.md entry for this, just a moment.

**Comment by mnylen** [comment]
Rebased to master, so now there shouldn't be any merge conflicts either.

**Comment by michaelklishin** [comment]
Welp, we do use `clojure.walk` in some areas — which is fine, those methods are unlikely to be invoked on the hot path.

Fixed by #159.

**Comment by michaelklishin** [comment]
@mnylen thank you. We can release a new beta today if you want, unless, of course, you may be looking into any other issues soon :)

**Comment by mnylen** [comment]
@michaelklishin, no problem. Go ahead with the beta 4 if you want. I can take a look on other issues, but I'm not sure if I have time for that this week.
