### ISSUE TITLE
index/stats options have no effect

### ISSUE THREAD

**Issue by neverfox** [clojurewerkz/elastisch#162]
You get the full response back no matter what you set. I think this has to do with the fact that the source sets them as query parameters, but the current ES documentation doesn't show them being used that way.

**Comment by michaelklishin** [comment]
Feel free to dig deeper. ES API certainly does change between releases.

**Comment by neverfox** [comment]
Since at least 1.3, they dropped stat types as query parameters. They now must be accessed as endpoints. For example, the url for `:docs true` should be `/_stats/docs` rather than `/_stats?docs=true`. The tests for `index.stats` wouldn't have caught this because it looks like they are mostly placeholder tests that were never fully fleshed out. They check for the most basic response but not whether it adapts to different settings. I have started on a PR but some of the function signatures around building up urls may need some refactoring to make this work elegantly.

**Comment by michaelklishin** [comment]
Fixed by #164.
