### ISSUE TITLE
native document/update-with-script broken

### ISSUE THREAD

**Issue by loganlinn** [clojurewerkz/elastisch#165]
`clojurewerkz.elastisch.native.document/update-with-script` throws exception when you call it. It's calling [`clojurewerkz.elastisch.native.conversion/->update-request`](https://github.com/clojurewerkz/elastisch/blob/860a0543300237c6857c422777522a17fc68bb13/src/clojurewerkz/elastisch/native/conversion.clj#L430) with incorrect arguments:

https://github.com/clojurewerkz/elastisch/blob/860a0543300237c6857c422777522a17fc68bb13/src/clojurewerkz/elastisch/native/document.clj#L132-L142

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at clojurewerkz.elastisch.native.conversion$__GT_update_request.invoke(conversion.clj:442)
	at clojurewerkz.elastisch.native.document$update_with_script.invoke(document.clj:138)
```

**Comment by loganlinn** [comment]
This appears to be the breaking change: https://github.com/clojurewerkz/elastisch/commit/800882cb2fcfc9304a4486f28b9423daeaac47e3#diff-27d7ee08d1c06ad745d07f058848fc03L431

**Comment by michaelklishin** [comment]
@loganlinn please submit a PR, since you seem to understand what exactly the issue is.
