### ISSUE TITLE
Convenience function for reindexing all documents in an index

### ISSUE THREAD

**Issue by ccfontes** [clojurewerkz/elastisch#175]
[Here is an explanation on how to reindex all the documents](https://www.elastic.co/blog/changing-mapping-with-zero-downtime). It goes on to say many client APIs already do all that work for the users with something like `reindex()`.
![screen shot 2015-09-04 at 18 51 27](https://cloud.githubusercontent.com/assets/2167559/9690726/163d03e8-5336-11e5-850c-695cdb62a6e3.png)

Is there something like `reindex` in this library or plans to implement it?

**Comment by michaelklishin** [comment]
@ccfontes there is no. This library is fairly mature and driven primarily by user requests. Feel free to look into it, it sounds like a very easy thing to add.

**Comment by ccfontes** [comment]
@michaelklishin thanks for taking the time to check this. I should need to implement this soon.

**Comment by michaelklishin** [comment]
@ccfontes any updates on this?

**Comment by ccfontes** [comment]
I have this working:
```clj
(defn reindex [^Connection conn]
  (let [query-res (clojurewerkz.elastisch.rest.document/search-all-indexes-and-types
                    conn
                    {:query (clojurewerkz.elastisch.query/match-all) :size 10000000})
        data (->> query-res
               :hits
               :hits
               (map #(merge (select-keys % [:_type :_index :_id]) (:_source %))))
        insert-ops (clojurewerkz.elastisch.rest.bulk/bulk-index (map #(dissoc % :_id) data))
        delete-ops (clojurewerkz.elastisch.rest.bulk/bulk-delete data)]
    (clojurewerkz.elastisch.rest.bulk/bulk conn insert-ops)
    (clojurewerkz.elastisch.rest.bulk/bulk conn delete-ops)
    query-res))
```
Size needs to be fixed.

I'm returning the query results in case reindex doesn't do its job well, so the user can back the data.

I didn't see other implementations of `reindex` yet. Maybe there are some better ideas.

**Comment by ccfontes** [comment]
I did some testing regarding `:settings` and `:mappings` changes, and found they weren't updated. So I came up with new code. There are some things to be fixed like `:query` `:size`, being general for all indexes, and handling of the case where the input `index` is not an alias yet, in an atomic way, if that is possible.

```clj
(defn- create-rand-idx [conn idx]
  (loop []
    (let [new-idx (int (* 1000 (rand)))]
      (if (clojurewerkz.elastisch.rest.index/exists? conn new-idx)
        (recur)
        (str idx "-v" new-idx)))))
```
```clj
(defn reindex [^Connection conn idx idx-opts & [last-version]]
  (if (clojurewerkz.elastisch.rest.index/exists? conn idx)
    (let [from-idx (some->> last-version (str idx "-v"))
          to-idx (create-rand-idx conn idx)
          query-res (clojurewerkz.elastisch.rest.multi/search-with-index
                      conn
                      idx
                      [{} {:query (clojurewerkz.elastisch.query/match-all) :size 10000000}])
          query-res (if (-> query-res :hits :hits seq) query-res bla)
          data (->> query-res
                 :hits
                 :hits
                 (map #(merge (select-keys % [:_type :_index :_id]) (:_source %)))
                 (map #(assoc % :_index to-idx)))
          insert-ops (clojurewerkz.elastisch.rest.bulk/bulk-index (map #(dissoc % :_id) data))]

      (clojurewerkz.elastisch.rest.index/create conn to-idx idx-opts)
      (clojurewerkz.elastisch.rest.bulk/bulk conn insert-ops)

      (if last-version ; FIXME check instead: (alias? idx) or (index? idx)
        (do (clojurewerkz.elastisch.rest.index/update-aliases conn
                [{:remove {:alias idx :index from-idx}}
                 {:add {:alias idx :index to-idx}}])
            (clojurewerkz.elastisch.rest.index/delete conn from-idx))
        (do (clojurewerkz.elastisch.rest.index/delete conn idx)
            (clojurewerkz.elastisch.rest.index/update-aliases conn
              [{:add {:alias idx :index to-idx}}])))

      query-res)

    [{:error "IndexMissingException[[kanasubs] missing]"}]))
```

**DISCLAIMER** Backup your elastic data first.
First time usage: `(reindex conn "my-index") `
General usage: `(reindex conn "my-alias" 123)`

To get the last index, do: `curl 'kanasubs.com:5432/_cat/indices?v'`
I cannot find the listing of indices implemented anywhere. Where can I find it?

**Comment by michaelklishin** [comment]
After giving it some thought, I think this function may end up being more opinionated that I expected and thus we shouldn't have it in Elastisch until a proven solution emerges.

**Comment by ccfontes** [comment]
You're right.
I'll still update improvements to the function if you don't mind. It can still be useful, even if too opinionated to become integrated in the library.

**Comment by ccfontes** [comment]
Removed `idx-opts` from `reindex` inputs.
