### ISSUE TITLE
remove duplicates in search results

### ISSUE THREAD

**Issue by ccfontes** [clojurewerkz/elastisch#176]
Wouldn't it be nice to have a function that removes entries with `:_source` dups in search results?

The following entries would be instances of duplication:
```clj
[{:_index "spam", :_type "eggs", :_id "AU_L4g6-iapqZBYOs1ss", :_score 1.0, :_source {:a 1, b 2}}
 {:_index "spam", :_type "eggs", :_id "AU_L4g6-iapqZBYOs1r5", :_score 1.0, :_source {:a 1, b 2}}]
```
The problem: It already happened to me inserting the same data twice.

Possible to do it with this one liner: 
```clj
(update-in es-data [:hits :hits] #(distinct-by :_source %))
```
but distinct-by is not shipped with Clojure.

**Comment by michaelklishin** [comment]
@ccfontes if an ES query returns duplicate results, is it really the client's responsibility to deduplicate? I'm not sure. Please investigate what the response contains, e.g. with curl.
