### ISSUE TITLE
How can I use size and from query parameters with search queries?

### ISSUE THREAD

**Issue by dahlie** [clojurewerkz/elastisch#177]
I'm implementing an API for web app which uses infinite scroll to display search results. Is there any way to leverage ```size``` and ```from``` query parameters in search queries (as documented here: https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html)?

**Comment by michaelklishin** [comment]
Pass them as [one of the options](https://github.com/clojurewerkz/elastisch/blob/master/test/clojurewerkz/elastisch/rest_api/search_test.clj#L44), REST client should pass everything through.

Please ask questions on the mailing list.
