### ISSUE TITLE
Specifying routing key while using search api

### ISSUE THREAD

**Issue by raunakb94** [clojurewerkz/elastisch#180]
I am trying to use the document search api and specify the routing key as 
(esd/search conn index-name index-type query :routing routing-key),
But at the end of the search request i found out that the query hits all the shards of the index(Which comes as a part of the response body from elasticsearch under the shards-hit keyword). Moreover the Http Url formed also doesnot contains a ?routing=routing-key extension added to it.

**Comment by michaelklishin** [comment]
`:routing` should be [passed to query params](https://github.com/clojurewerkz/elastisch/blob/master/src/clojurewerkz/elastisch/rest/document.clj#L201).

What version do you use? Can you provide a test case?

**Comment by raunakb94** [comment]
I am using elastisch 2.1.0. If possible can you suggest a test-code for any routing key index name and any type.

**Comment by michaelklishin** [comment]
@raunakb94 we have the docs. Please refer to them. If you have a test case we can use, I'm happy to triage this.

**Comment by raunakb94** [comment]
Thanks for the time!! It was helpful!! I solved the issue.
