### ISSUE TITLE
Documentation is Off

### ISSUE THREAD

**Issue by adomokos** [clojurewerkz/elastisch#185]
As I am going through the documentation I noticed an incorrect example. 

The example states `[clojurewerkz.elastich.response.response :as esrsp]`, it should be `[clojurewerkz.elastish.native.response :as esrsp]`. I'd be happy to submit a PR if someone could provide the github repo for the documentation website. Thanks!

![native_response](https://cloud.githubusercontent.com/assets/80530/11609245/58fc474e-9b47-11e5-845f-849865fb9af8.png)

**Comment by adomokos** [comment]
Found another one, the "c" is missing.

![missing_char](https://cloud.githubusercontent.com/assets/80530/11609528/98c393e4-9b4e-11e5-9486-ae4bc35b2135.png)

**Comment by michaelklishin** [comment]
@adomokos the docs are [open source](https://github.com/clojurewerkz/elastisch.docs).
