### ISSUE TITLE
Not able to connect to elastic serach

### ISSUE THREAD

**Issue by chaithrar** [clojurewerkz/elastisch#190]
Hi,

I am trying to connect to Elastic search via rieman but getting below error while connecting to it.
Can you please tell me whats I could be missing

ERROR [2015-12-23 22:10:22,680] main - riemann.bin - Couldn't start
java.lang.RuntimeException: No such var: esr/connect!, compiling:(riemann/elastic.clj:91:3)
        at clojure.lang.Compiler.analyze(Compiler.java:6464)
        at clojure.lang.Compiler.analyze(Compiler.java:6406)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3665)

**Comment by michaelklishin** [comment]
Please ask questions on the mailing list.

Riemann assumes an old version of Elastisch, which has that function.
