### ISSUE TITLE
v2.2.0 not on Clojars

### ISSUE THREAD

**Issue by matthiasn** [clojurewerkz/elastisch#191]
Hi, I see you've tagged v2.2.0 but it's not on Clojars. Would you mind publishing it? Cheers and Happy New Year, Matthias

**Comment by henriklundahl** [comment]
There are a lot of problems with Clojars right now, which probably is the reason for it not being published yet.

**Comment by matthiasn** [comment]
Hard say, I published a handful of artifacts today with zero problems.

**Comment by michaelklishin** [comment]
@matthiasn Clojars was down for several hours yesterday when I did the tagging. It is published now.

**Comment by matthiasn** [comment]
Great thanks
