### ISSUE TITLE
ES 3.x ...?

### ISSUE THREAD

**Issue by royaldark** [clojurewerkz/elastisch#196]
Is it a typo in the readme when it says `As of January 2016, after the 2.2 release, Elastisch development targets ElasticSearch 3.x.`? I assume it should say ElasticSearch 2.x?

**Comment by michaelklishin** [comment]
master will target 3.x as soon as we get at least most of the API working on 3.x. It is not a typo.

**Comment by royaldark** [comment]
So will ES 2.x support be skipped? Later in the readme it says `Elastisch does not currently support ElasticSearch 2.x. It will be our focus after the (Elastisch) 2.2 release.`

**Comment by michaelklishin** [comment]
Err, I'm lost in ES versions. No, the goal is to target 2.x, of course, as 3.x doesn't yet exist :)
