### ISSUE TITLE
clj-http :throw-exceptions option

### ISSUE THREAD

**Issue by loganmhb** [clojurewerkz/elastisch#198]
Why does elastisch not allow the user to set clj-http's :throw-exceptions option as it does other options? I'd prefer to be able to throw an exception when an elastisch call fails -- this would be a nice usability improvement unless it would break something else. Thanks!

**Comment by michaelklishin** [comment]
I'm OK with allowing it to be changed as long as the default stays the same. Feel free to submit a PR.

**Comment by michaelklishin** [comment]
Fixed in #199 but #200 might be an even better way to go.
