### ISSUE TITLE
Support for search templates?

### ISSUE THREAD

**Issue by KeeganMyers** [clojurewerkz/elastisch#201]
I have incorporated elastisch into a long running project that has a requirement for users to build and store sanitized queries. After reviewing the documentation it appears that search templates in Elasticsearch would achieve this well. However, after reviewing the documentation and searching the source for elastisch I was not able to find any way to use search templates. 

Has search template functionality been incorporated into elastisch?
If it has not was there a specific limitation in the java libraries you appear to be using that prevented this functionality?

Otherwise dependent on my upcoming workflow I may be able to open a pull request to add search templates.

For reference sake I am using version 2.2.1 of elastisch via the native components along with version 1.7

**Comment by michaelklishin** [comment]
I think the answer is "nobody to date needed it, so no".

**Comment by KeeganMyers** [comment]
Roger, from cross referencing various version of the Elasticsearch documentation I found that this works well for creating the  search template 

(esd/create
 conn ".scripts" "mustache" {:template {:filter {:bool {:must [{:term {:name "{{name}}"}}] }} }} :id "test-template")

And the template can be retrieved using a standard get by id. However, I am still struggling with rendering the template. I will try to provide updates and/or a pull request in the event that I can resolve this, or make some significant discoveries.

**Comment by michaelklishin** [comment]
@KeeganMyers so #202 fixes this for the binary client. Do we need to do anything else (e.g. update the REST one to match) or can this be closed now?

**Comment by KeeganMyers** [comment]
I think this can be closed. It would be nice ideally for the native and http clients to remain similar. Unfortunately I'm working on borrowed time as it is and can't address issues that fall outside the scope of my current project.
