### ISSUE TITLE
ES 2.x support

### ISSUE THREAD

**Issue by royaldark** [clojurewerkz/elastisch#204]
I'm hoping this issue can be a coordinating place for ES 2.x support in Elastisch.

I didn't see any 2.x-related commits here yet, so I've begun cleaning up some of the major breaking changes on my fork: https://github.com/royaldark/elastisch/tree/es-2x.

It's gone well so far, but I haven't sunk too much time in yet :) I'm fixing compile errors one NS at a time to begin.

**Comment by michaelklishin** [comment]
@royaldark thank you!

**Comment by royaldark** [comment]
I have Elastisch compiling & testing successfully against ES 2.0 now. Most of the changes address the removal of features from ES:
- More Like This API
- Mapping deletion
- Index status API
- Delete by query
- Facets

There is one failing test (`test-avg-aggregations`), but it fails identically on master for me.

I guess the next step, where some pointers would be helpful, is determining what features were added to ES 2.0 that need to be supported in Elastisch.

**Comment by michaelklishin** [comment]
@royaldark I'd recommend merging what you've got so far and producing a first 3.0 preview release. I'd be happy to take a look at the failing test. Please submit a PR?

**Comment by royaldark** [comment]
Done. https://github.com/clojurewerkz/elastisch/pull/205

**Comment by michaelklishin** [comment]
We are maybe 60% there with the test suite thanks to #205 and a few more fixtures tweaks. Still a couple of dozens of errors and failures to go, and several test namespaces to uncomment.

**Comment by MerelyAPseudonym** [comment]
I was going through the failing tests for `clojurewerkz.elastisch.rest` namespaces recently. I'll make a branch available soon.

**Comment by michaelklishin** [comment]
@MerelyAPseudonym I wouldn't mind adding you as a collaborator to this repo if this would make things easier for you. Let me know.

**Comment by MerelyAPseudonym** [comment]
I've pushed my changes to [the `es2-WIP` branch in my fork](https://github.com/MerelyAPseudonym/elastisch/tree/es2-WIP). In that branch, all of the non-native tests up through `clojurewerkz.elastisch.rest-api.indices-test` pass.

Regarding your offer @michaelklishin: that sounds great. I'll still create PRs for anything I'm not 100% sure about, but I'd be happy to work alongside you and @royaldark on `master`. :smile:

**Comment by timgluz** [comment]
@MerelyAPseudonym  hi, is there any tests/task left? i
is there a way we can coordinate tasks?

**Comment by timgluz** [comment]
I just fixed the last failing test of REST-client on @MerelyAPseudonym's  es2-WIP branch and open pull-request there;

**Comment by michaelklishin** [comment]
@timgluz thank you! Since @MerelyAPseudonym is now a member of this repo, why not submit the PR for this repo?

By the way, I'd be happy to add you as a collaborator if you see any value in it.

**Comment by timgluz** [comment]
OK, i will do it tomorrow, it's quite late here - i must pull the latest changes from the master branch and resolve some git conflicts before i can do pull-request.

Thanks for your offer, but i'll pass it - quite happy with my current status.

**Comment by MerelyAPseudonym** [comment]
Hey all, I should have plenty of time to devote to this tomorrow.

@timgluz I'm really excited to check out your PR =)

**Comment by mbuczko** [comment]
hey guys, is there any chance to get elastisch running with newest elastic 2.3.x soon ?

**Comment by timgluz** [comment]
yes, i'm going run test against 2.3 tomorrow and there shouldn't be much of breaking changes. so i guess RC will land some point next week.

**Comment by michaelklishin** [comment]
@mbuczko @timgluz this is open source software. Those who need compatibility with ES 2.x soon should consider contributing instead of asking others to do all the work.

**Comment by mbuczko** [comment]
Well, I'm not asking others to do all the work, I'm just curious what's the status of current work on 2.x branch to not duplicate work already done. It's great to hear that @timgluz actually finished his changes and I'll be really happy to support him in testing or contributing to upcoming release candidates.

**Comment by timgluz** [comment]
I managed to get Travis to [work again](https://github.com/timgluz/elastisch/tree/travis-fix) by replacing default ES that Travis provides with Dockerized version;

`native-api/aggregation` tests are still failing and the reason seems to be quite silly - it fails to cleanup fixtures : https://travis-ci.org/timgluz/elastisch/builds/124289146

**Comment by mbuczko** [comment]
I tried native api out with some nested aggregations on elastic 2.3 and looks like it works pretty nice. Amazing job, thanks :)

**Comment by michaelklishin** [comment]
@mbuczko thank you for the feedback. We have quite a bit of things to revisit, add, and edit (the docs).

**Comment by MerelyAPseudonym** [comment]
Sorry guys, I've been really busy with work, trying to get a project over the finish line. Once that's done, though, I should have more time again to devote to Elastisch. Anyway, I'm happy to see that @michaelklishin was able to help @timgluz integrate his changes!

**Comment by MerelyAPseudonym** [comment]
By the way, @timgluz, when I tested [your other PR](https://github.com/MerelyAPseudonym/elastisch/pull/1) I was able to get all of the (REST-client only) tests to pass against ES 2.0, ES 2.1, ES 2.2 **and** ES 2.3!

**Comment by MerelyAPseudonym** [comment]
@michaelklishin How do you want to handle updating [`elastisch.docs`](https://github.com/clojurewerkz/elastisch.docs)? Should there be a `3.0-updates` branch?

**Comment by mbuczko** [comment]
I did some more tests and I put query in a loop executing aggregation once a 3 sec. After a few seconds I got:

     java.lang.OutOfMemoryError: unable to create new native thread

I'll try to dig a bit deeper in the evening to see what's going on.

**Comment by michaelklishin** [comment]
@mbuczko can we please move these discussions to the mailing list? It's not exactly great that all kinds of things are discussed in this issue. Elastisch cannot be blamed for your JVM running out of kernel threads when you do something in a loop.
