### ISSUE TITLE
Release 3.0.0-beta1

### ISSUE THREAD

**Issue by michaelklishin** [clojurewerkz/elastisch#214]
Now that https://github.com/clojurewerkz/elastisch/issues/204 is merged and key operations are supported (but the work towards 3.0 is by no means done), we should a milestone release.

**Comment by smaant** [comment]
I'm developing a service backed by elasticsearch now and initially I was going to use ES 2.3 but discovered it's not supported by elastisch. My service is going to hit production in about a month, do you think it'll be completely insane to start developments using current master of elastisch expecting it'll be close to 3.0 release in a month?

**Comment by michaelklishin** [comment]
I wouldn't expect it to be close to 3.0 in a month but it might very well be reasonably stable for you to start today.

**Comment by royaldark** [comment]
@michaelklishin Is there a list of what still needs to be accomplished for 3.0?

**Comment by MerelyAPseudonym** [comment]
@royaldark I'm curious about that too. In my opinion, we're ready for a beta release.

FWIW, at my job we're in the process of upgrading to Elasticsearch 2.3.3, so despite my being busy with other things as of late, very soon I'll be putting Elastisch 3 through its paces.

**Comment by michaelklishin** [comment]
@royaldark porting the original test suite to the extent we can (some things have to be dropped), then stabilizing it and updating the docs. Except for the docs part we are most of the way there, so I think releasing a beta of 3.0 some time this week is very realistic.

**Comment by michaelklishin** [comment]
I'm waiting for updates/responses on #221 and then doing a beta release.

**Comment by michaelklishin** [comment]
`3.0.0-beta1` is up on Clojars.

**Comment by stuarth** [comment]
Any thoughts on cutting a new beta release @michaelklishin ? Be great to have one with work that's been done since `3.0.0-beta1`!

**Comment by michaelklishin** [comment]
@stuarth will do an rc tomorrow.

**Comment by stuarth** [comment]
thanks!

**Comment by michaelklishin** [comment]
FTR, I haven't forgotten about this, just have been a little swamped with other projects. Sorry.
