### ISSUE TITLE
Proposal: require options-maps instead of pseudo keyword arguments

### ISSUE THREAD

**Issue by MerelyAPseudonym** [clojurewerkz/elastisch#215]
In the same vein as [a similar change in Langohr](https://github.com/michaelklishin/langohr/blob/6aa36f823e46c82cfa434c266bdc04d975f083ac/ChangeLog.md#options-as-maps), I propose that Elastisch functions accept their options as proper Clojure maps, rather than as pseudo keyword arguments. Furthermore, including this change as a part of the 3.0 release makes sense to me, since we'll already be including some changes that break backwards compatibility anyway.

**Comment by michaelklishin** [comment]
@MerelyAPseudonym don't we already do that in `2.x` (but pseudo-kwargs are still supported)? I'm not against requiring maps but we'd need to rework all docs.

Anyhow, feel free to look into it :)

**Comment by MerelyAPseudonym** [comment]
This work is nearly done. I have a branch in my repo that passes all of the tests, but I still need to finish cleaning up the history—something I hope and expect to get to tomorrow.

**Comment by dtenny** [comment]
Just for the record as a contrary opinion, I wholly disagree with the rationale for breaking the API in this way.  It serves no functional purpose (i.e. no net gain in capability, no fix to egregious bugs), and it _breaks existing code_ without benefit of a real purpose for doing so.  Furthermore, it breaks code in a way which is not detected at compile time, so the poor users of the API will find out the hard way at runtime.

That said, I'm not up to speed on what other breaking changes are in 3.0, but if they're more of the same in the vein of this change, then I think they're bad for the same reasons.

**Comment by MerelyAPseudonym** [comment]
@dtenny I _do_ think that including a sorta explanation/rationale in the changelog for this switch would be a good idea. (Perhaps I even should have held off on submitting the PR until writing such a thing.)

So, with the goal of getting Elasticsearch 2 compatibility to our users ASAP, I’m open to the idea of reverting #220 temporarily. I envision a roadmap something like the following:
- Elastisch 3: Elasticsearch 2 compatibility
- Elastisch 4: various cleanup, *including the kwargs→options-map breaking change*
- Elastisch 5: Elasticsearch 5 compatibility
  - (no, we wouldn’t be skipping Elasticsearch releases; Elastic is skipping numbers 3 and 4 to unify the version numbers of their assorted products.)

@michaelklishin what do you think?

**Comment by MerelyAPseudonym** [comment]
> Furthermore, it breaks code in a way which is not detected at compile time, so the poor users of the API will find out the hard way at runtime.

I overlooked this because I was primarily using Cursive; it statically detects the bad arity and highlights the error for you:
<img width="441" alt="Cursive bad-arity reporting" src="https://cloud.githubusercontent.com/assets/831177/16201040/be507930-36dd-11e6-96d0-2aae73ed9c84.png" />

I assumed the same thing would happen during compilation, but a couple experiments with `lein compile :all` have shown otherwise.

**Comment by MerelyAPseudonym** [comment]
Regarding the benefits of options-maps vs kwargs: the main issue is that kwargs do not compose well, and a side-benefit is that the `:arglists` metadata can/will become more meaningful.

Good discussions about options-maps and kwargs can be found at:
- <http://yellerapp.com/posts/2015-03-22-the-trouble-with-kwargs.html>
- Zach Tellman’s [_Elements of Clojure_](http://elementsofclojure.com/)

The latter contains the specific prescription to reserve kwargs for macros, which seems like solid advice to me.

The `:arglists` metadata enhancements isn’t a consequence of options-maps _per se_, but by ceasing to support _both_ options-maps and kwargs. Previously, Elastisch needed to call [`clojurewerkz.elastisch.arguments/->opts`](https://github.com/clojurewerkz/elastisch/blob/v2.2.0/src/clojurewerkz/elastisch/arguments.clj#L3-L9) in nearly every function ([example](https://github.com/clojurewerkz/elastisch/blob/v2.2.0/src/clojurewerkz/elastisch/native/index.clj#L257)) in order to support both styles of providing parameters. An unfortunate consequence of supporting both is that most functions’ arglists contain an opaque trailing `& args`, rather than details about the options. (I.e., rather than `:arglists` metadata containing `([conn template-name {:keys [template settings mappings order]}])` or `([conn template-name & {:keys [template settings mappings order]}])`, it merely contains `([conn template-name & args])`.)

**Comment by michaelklishin** [comment]
@dtenny have you tried composing a map of options to then pass them to a function that uses pseudo-kwargs? Try it. That alone is a worthy gain.

**Comment by michaelklishin** [comment]
On top of the previously voiced arguments, this change is for Elastisch 3.0, which has plenty of breaking API changes simply because ElasticSearch 2.x has them.

**Comment by dtenny** [comment]
I understand the goals of making these functions fit the clojure mold better.  What I have a problem with is breaking existing code when it isn't necessary.  Libraries that deliberately break working code _when there are alternatives_ is very high up on my evil things to do meter.

In this case the alternatives are not pretty.  You could provide new functions with new signatures, leave it to users to wrap existing functions+signatures if they want more composability, and other equally unpretty solutions.

Anyway, the decision is yours of course, I can only offer my opinion.  Naturally if you document the breaking changes that mitigates things a bit, I know this is a work in progress at the moment.  But from a client perspective, I have code that works and relies on existing versions, and so a version bump that breaks code in undocumented and generally (statically) undetectable ways is not welcome.  It leaves developers explaining to users of their functionality why the project is late or the system is breaking after discovering it the hard way.

**Comment by michaelklishin** [comment]
Elastisch has been doing a hybrid thing for years. Backwards compatibility has been an important factor for ClojureWerkz projects and we have 5 years behind us to back this claim. For a new major versions that target an ElasticSearch release with breaking changes, *keeping broken API parts* would be the most evil decision possible.

Sorry but you are advocating for not changing certain things *ever*. I've seen all too well how this works out in 10 year old projects.

**Comment by michaelklishin** [comment]
I am locking this because there is no point to debate something that's the right thing to do for 3.0 and that's already been merged.
