### ISSUE TITLE
Proposal: treat docstrings as Markdown rather than plain text

### ISSUE THREAD

**Issue by MerelyAPseudonym** [clojurewerkz/elastisch#216]
To illustrate the difference, compare the following screenshots:
<img width="613" alt="clojurewerkz.elastisch.rest.document/create docstring as plain text" src="https://cloud.githubusercontent.com/assets/831177/14863340/4eaf0e36-0c83-11e6-8c4e-8b067639df31.png">

<img width="588" alt="clojurewerkz.elastisch.rest.document/create docstring as rich text via markdown" src="https://cloud.githubusercontent.com/assets/831177/14863348/5982ec1a-0c83-11e6-8674-c7bcfe57c745.png">

I've already done some initial work in [my `feature/markdown-docstrings` branch](https://github.com/clojurewerkz/elastisch/tree/feature/markdown-docstrings), in which you can see [the (minor) changes made to the `c.e.r.document/create` docstring](https://github.com/clojurewerkz/elastisch/commit/cc463e6683575f9b039a51a41e8695bd35ac2d20#diff-e827d6dd75132c87954dd4ccea9e4e13L36) to help it render prettily.

**Comment by MerelyAPseudonym** [comment]
I anticipate keeping incremental commits in my `feature/markdown-docstrings` branch until it's all ready to go. Since I doubt there will be any value in keeping the intermediate commits, when the time comes I'll probably rebase onto `master` and squash everything into a single commit.

**Comment by MerelyAPseudonym** [comment]
Anyway, @michaelklishin are you on board with this? I don't want to make broad changes across the codebase (even if they're just documentation changes) if you're opposed.

**Comment by michaelklishin** [comment]
👍

**Comment by MerelyAPseudonym** [comment]
cool, thanks!

**Comment by MerelyAPseudonym** [comment]
Something that is up for debate is which style to use for the code examples in the docstrings: indents or “fences”.

<pre>
Description.

Example:

    (foo "bar")
    (fizz (buzz))
</pre>

<pre>
Description.

Example:

```clojure
(foo "bar")
(fizz (buzz))
```
</pre>

The first style is arguably a little more readable when viewing the raw docstring text, but the second includes a little more style information in the generated HTML.

**Comment by michaelklishin** [comment]
We use a Markdown library that should support "fences." I personally like them and use them very often on GitHub.

**Comment by MerelyAPseudonym** [comment]
I'll stick with fences then. Thanks for the input!

**Comment by MerelyAPseudonym** [comment]
(fences were my preference as well, though it's a very mild preference)
