### ISSUE TITLE
Many links to official Elasticsearch documentation are out of date

### ISSUE THREAD

**Issue by MerelyAPseudonym** [clojurewerkz/elastisch#217]
For example, [the docstring of `clojurewerkz.elastisch.native.index/create`](https://github.com/clojurewerkz/elastisch/blob/c985dffb279f16912e1af9a1e84fe07f0f56dc35/src/clojurewerkz/elastisch/native/index.clj#L67) includes a link to http://www.elasticsearch.org/guide/reference/api/admin-indices-create-index.html, which redirects to https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html. Most of the links in the Elastisch codebase are similar, in that they refer to some page at elasticsearch.org that, if followed, redirects to a corresponding page at elastic.co. (However, a few links do not redirect successfully, such as https://github.com/clojurewerkz/elastisch/blob/c985dffb279f16912e1af9a1e84fe07f0f56dc35/src/clojurewerkz/elastisch/rest/index.clj#L247.)

**Comment by MerelyAPseudonym** [comment]
Btw, I have a WIP branch at https://github.com/merelyapseudonym/elastisch/tree/fix-URLs-for-3.x.

**Comment by MerelyAPseudonym** [comment]
In addition to updating the links to point to elastic.co instead of elasticsearch.org, I'd like to take the opportunity to include the Elasticsearch version number in the URL. By including a link to (for example) <https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-create-index.html> instead of <https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-create-index.html>, users of Elastisch will be directed to the documentation that corresponds to the version of Elasticsearch that _that version of Elastisch targets_. Otherwise, when Elasticsearch 5 is released (Elasticsearch is skipping versions 3 and 4), suddenly all of the Elastisch 3 docstrings would be directing users to the "wrong" documentation.

@michaelklishin What do you think?

**Comment by MerelyAPseudonym** [comment]
Btw, as a side benefit of figuring out what the latest URLs should be, I've been finding [additional](https://github.com/MerelyAPseudonym/elastisch/commit/087f640d2ffa8019c955e348fbe9f992e41ccc67) [features](https://github.com/MerelyAPseudonym/elastisch/commit/3826729cbc79fa6129e204549a1e33f621d6f426) that were removed in Elasticsearch 2 and thus probably be removed from Elastisch 3.

**Comment by michaelklishin** [comment]
@MerelyAPseudonym yup. Thank you for doing this incredibly tedious work.

**Comment by MerelyAPseudonym** [comment]
My thoughts on this task have evolved a bit: instead of batch-updating every URL, I’d like to only update a docstring’s URL after verifying that the content of that docstring is up to date *and consistent* with what the user would find at the documentation linked to by the URL. So now I'm treating the URLs to elasticsearch.org as empty checkboxes, indicating that the docstring has not been polished yet.

I will prioritize the docstrings that include *broken* links.

If I'm going to be updating the docstrings one-by-one, I think it might be better to do the changes directly on `master`, rather than collecting all “fixing URLs” changes in a feature branch until all of the URLs have been fixed. Any opinion there, @michaelklishin?

**Comment by michaelklishin** [comment]
@MerelyAPseudonym no objections to doing incremental changes in master.

**Comment by michaelklishin** [comment]
In many cases it's a matter of a fairly simple replacement, e.g. 

http://www.elasticsearch.org/guide/reference/api/admin-indices-create-index.html => https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-create-index.html.

This is the last remaining item for 3.0, I should cover it next week.
