### ISSUE TITLE
Native get-mapping ignores index name in 2-arity version, returns all index mappings

### ISSUE THREAD

**Issue by JoshAaronJones** [clojurewerkz/elastisch#234]
The 2-arity version of `clojurewerkz.elastisch.native.index/get-mapping` ignores the `index-name` parameter, and would have no way of retrieving mappings for the specified `index-name`.  But beside simply returning a map of all indices, it seems that the map contains duplicate data, with cases like the following (in my example): `:locindex {:mappings {:get-together {:mappings {: ... }` where `locindex` and `get-together` are separate indices.

To demonstrate, I've included 
[output](https://github.com/clojurewerkz/elastisch/files/407111/get-mapping-1.txt) which contains the value returned from `(get-mapping conn "testidx")` to demonstrate the previously described behavior; 
[output](https://github.com/clojurewerkz/elastisch/files/407116/get-mapping-2.txt)
 from the 3-arity version of the function which correctly returns the index and mapping requested; and finally, the 
[browser output](https://github.com/clojurewerkz/elastisch/files/407118/rest-response.txt)
 from getting `http://localhost:9200/textidx`, which shows that there is only one mapping in this index.

The expected behavior would be that calling `get-mapping` with the connection information and an index name only, should return a map of the index and all mappings it contains.  Instead, the response is what is described above, which is all indices, plus duplicate data that makes it impossible to know what is actually a mapping in the index.

**Comment by michaelklishin** [comment]
Feel free to submit a pull request against the `2.2.x-stable` branch.

**Comment by JoshAaronJones** [comment]
I'm going to close this as it's quite old, I'm no longer actively using elastisch, and it is clearly not something anyone else really needs at the moment.
