### ISSUE TITLE
doc link is dead

### ISSUE THREAD

**Issue by nha** [clojurewerkz/elastisch#236]
The following link is dead:
http://clojureelasticsearch.info/articles/distribution.html

However it is referenced here:
http://clojureelasticsearch.info/articles/getting_started.html#what-to-read-next

It may be just the result of a transition between versions but I thought I would mention it here.

**Comment by michaelklishin** [comment]
It's not dead, it simply wasn't finished. Doc guides [have a separate repo](https://github.com/clojurewerkz/elastisch.docs).
