### ISSUE TITLE
Support bulk operations in the native client

### ISSUE THREAD

**Issue by michaelklishin** [clojurewerkz/elastisch#24]
We need to support bulk operations in the native client with the same Clojure API we
have in the REST one.

**Comment by mitchelkuijpers** [comment]
Just wanted to let you know I started working on this, and I am making some good progress :) Will try to have something ready by the end of this weekend.

**Comment by michaelklishin** [comment]
@mitchelkuijpers sounds good, thank you.

**Comment by mitchelkuijpers** [comment]
I have a first version working i currently give this structure back after a bulk operation:

```
{:took 8,
   :has-failures? false,
   :items
   [{:index "people",
     :type "person",
     :id "AUuxP_sQUECUznwbZ-36",
     :version 1,
     :op-type "create",
     :failed? false}
    {:index "people",
     :type "person",
     :id "AUuxP_sQUECUznwbZ-37",
     :version 1,
     :op-type "create",
     :failed? false}]}
```

I case of failure the failed? property will be true and a failure-message property will be added. I notice the rest api gives properties back like :_index and :_type. Do you think I should add those @michaelklishin ?

**Comment by michaelklishin** [comment]
@mitchelkuijpers yes, as aliases for `:index and `:type`, of course. We do this in other places. Better be compatible than sorry :)

**Comment by mitchelkuijpers** [comment]
@michaelklishin Added, and also ```:_index``` and ```:_version```. 

The only thing that I think we should not implement is: ```bulk-with-index``` and ```bulk-with-index-and-type```. This is kind of hairy to implement and this would mean I cannot reuse the ```->delete-request``` and the ```index->request``` functions from ```conversion.clj```. What are your thoughts on this?

**Comment by mitchelkuijpers** [comment]
After thinking about it some more I am leaning towards the option of reusing the bulk-index and bulk-delete functions from ```rest/bulk``` this way you can just switch the native and rest ```bulk```, ```bulk-with-index``` and ```bulk-with-index-and-type``` calls without changing anything :)

**Comment by michaelklishin** [comment]
That's fine. I find those functions a bit odd in the REST API. 100% compatibility is not the goal. If we can keep it at 95%, that's already huge for our users.

**Comment by michaelklishin** [comment]
@mitchelkuijpers so, native would delegate to REST? This should be made very clear in the docs because the two use different ports and some installations may be locked down to only one protocol at the firewall.

**Comment by mitchelkuijpers** [comment]
@michaelklishin  No Native would only re-use these functions from rest:

```
(def ^:private special-operation-keys
  [:_index :_type :_id :_retry_on_conflict :_routing :_percolate :_parent :_timestamp :_ttl])

(defn index-operation
  [doc]
  {"index" (select-keys doc special-operation-keys)})

(defn delete-operation
  [doc]
  {"delete" (select-keys doc special-operation-keys)})

(defn bulk-index
  "generates the content for a bulk insert operation"
  ([documents]
     (let [operations (map index-operation documents)
           documents  (map #(apply dissoc % special-operation-keys) documents)]
       (interleave operations documents))))

(defn bulk-delete
  "generates the content for a bulk delete operation"
  ([documents]
     (let [operations (map delete-operation documents)]
       operations)))
```
And then if you call bulk or the other two bulk functions (those are easy to implement this way) this will be transformed to either and IndexRequest or an DeleteRequest and we can simply call the native api :)

**Comment by michaelklishin** [comment]
@mitchelkuijpers ah, perfect. Feel free to extract them into a separate internal namespace, e.g. `elastisch.common.bulk`.

**Comment by mitchelkuijpers** [comment]
@michaelklishin :+1:

**Comment by michaelklishin** [comment]
@mitchelkuijpers any other way I can help you? I'd be very excited to see this feature added :)

**Comment by mitchelkuijpers** [comment]
I'll try to have a pull request ready tomorrow, had a busy week ^^

**Comment by michaelklishin** [comment]
Contributed by @mitchelkuijpers in #144.
