### ISSUE TITLE
Delete by query is not working with HTTP (wrong url?)

### ISSUE THREAD

**Issue by heeboA** [clojurewerkz/elastisch#248]
The delete by query function doesn't seem to work.

What I have in my code:
`(esd/delete-by-query conn index type {:range {:timestamp {:lte max-timestamp}}})`

Returns:
`{:found false,
 :_index "x",
 :_type "x",
 :_id "_query",
 :_version 1,
 :result "not_found",
 :_shards {:total 2, :successful 1, :failed 0}}`

If I use the same exact same query with "search", it finds the documents. I believe this is due to the fact that delete by query sends a DELETE to `http://127.0.0.1:9200/x/x/_query` with query as the request body param, while the Elastic [docs](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/docs-delete-by-query.html) suggest that the correct method is a POST to `http://127.0.0.1:9200/x/x/_delete_by_query` with the same body.

**Comment by michaelklishin** [comment]
@heeboA if this can be reproduced with ElasticSearch 2.x or 3.x, feel free to submit a pull request (with a test, please). Otherwise it's a 5.0 issue and 5.0 compatibility will be addressed after a 3.x-compatible GA release. There's an issue for that.

**Comment by joachimdb** [comment]
delete-by-query is not supported anymore by elasticsearch >= 2.0 unless an extension is installed, see https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/delete-by-query-plugin-reason.html

**Comment by michaelklishin** [comment]
@joachimdb thank you. Perhaps we should delete the function then? Or just update the docs for Elastisch 3.0 and remove in a later release?
