### ISSUE TITLE
Fix Delete By Query for Elasticsearch 5

### ISSUE THREAD

**Issue by hantuzun** [clojurewerkz/elastisch#256]
Elasticsearch 5 has updated Delete By Query methods with `POST` ...`/_delete_by_query` signatures.

I've fixed elastisch for that, but forking from
@wneirynck's open pull request [#252](https://github.com/clojurewerkz/elastisch/pull/252) here: https://github.com/hantuzun/elastisch

**Comment by michaelklishin** [comment]
@hantuzun you can change base fork and branch when creating a pull request. Please do that instead.

**Comment by hantuzun** [comment]
@michaelklishin, I'd like to do that when Elastisch will have an Elasticsearch 5.x branch...

**Comment by hantuzun** [comment]
Hi @michaelklishin, 

Since @wneirynck's PR is now merged to the master, should I create a new PR for this fix?

**Comment by michaelklishin** [comment]
@hantuzun please do, thank you!
