### ISSUE TITLE
3.0.1 release date?

### ISSUE THREAD

**Issue by Jarzka** [clojurewerkz/elastisch#269]
Hi

Related to this issue: https://github.com/clojurewerkz/elastisch/issues/266

I wonder if this issue was closed by mistake. The PR was merged and 3.0.0 was released. However, 3.0.0 is the current release we are using, so I believe the right release version should have been 3.0.1. Can you please upload it to Clojars if it is ready?

**Comment by michaelklishin** [comment]
Will do.

**Comment by michaelklishin** [comment]
`3.0.1` is out. Sorry it takes me forever :(

**Comment by Jarzka** [comment]
Great, thanks! Just remember to update the version in readme file too ;)
